#!/bin/bash

# Check if correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <node or pod> <namespace>"
    exit 1
fi

# Define command-line arguments

RESOURCE_TYPE=$1
NS=$2 
header="true"
tmp_file=$(mktemp)

# Retrieve resource usage statistics from Kubernetes
# echo "R-TYPE NS NAME CPU MEM" | column -t -s ' '
kubectl top $RESOURCE_TYPE -n $2 | tail -n +2 | while read -r line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  text="$RESOURCE_TYPE $NS $NAME $CPU $MEMORY"
  
  if [ "$header" = "true" ]; then
    echo "R-TYPE NS NAME CPU MEM" 
    header="false"
  fi
  echo $text 
done > $tmp_file
cat $tmp_file | column -t -s ' '
rm $tmp_file
